version: '3.8'

services:
  db:
    image: postgres:15
    container_name: search_postgres
    environment:
      POSTGRES_USER: ir_user
      POSTGRES_PASSWORD: ir_password
      POSTGRES_DB: ir_corpus
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: